from __future__ import annotations

import json
import sys
from pathlib import Path

DEMO_DIR = Path(__file__).resolve().parent
BACKEND_DIR = DEMO_DIR.parent
SRC_DIR = BACKEND_DIR / "src"
sys.path.insert(0, str(SRC_DIR))

from core.agents.orchestrator import OrchestratorAgent  # noqa: E402
from core.models.claim import ClaimRequestData, SupportingDocumentData  # noqa: E402


def main() -> None:
    cases = json.loads((DEMO_DIR / "claims.json").read_text(encoding="utf-8"))
    results = []
    for index, case in enumerate(cases, start=1):
        policy_path = DEMO_DIR / "policies" / case["policy"]
        image_path = DEMO_DIR / "images" / case["image"] if case.get("image") else None
        image_bytes = image_path.read_bytes() if image_path and image_path.exists() else None
        supporting_documents = []
        for filename in case.get("supporting_documents", []):
            document_path = DEMO_DIR / "supporting_documents" / filename
            text = document_path.read_text(encoding="utf-8")
            supporting_documents.append(
                SupportingDocumentData(
                    filename=filename,
                    document_type="demo_supporting_document",
                    text=text,
                    text_length=len(text),
                )
            )
        request = ClaimRequestData(
            insurance_type=case["insurance_type"],
            claim_description=case["description"],
            incident_date=case.get("incident_date"),
            policy_text=policy_path.read_text(encoding="utf-8"),
            policy_filename=policy_path.name,
            damage_image_filename=image_path.name if image_bytes else None,
            damage_image_size=len(image_bytes) if image_bytes else None,
            damage_image_mime_type="image/png" if image_bytes else None,
            damage_image_bytes=image_bytes,
            supporting_documents=supporting_documents,
        )
        result = OrchestratorAgent().analyze(request)
        record = {
            "id": case["id"],
            "title": case["title"],
            "policy": case["policy"],
            "description": case["description"],
            "expected_behavior": case["expected_behavior"],
            "image": case.get("image"),
            "supporting_documents": case.get("supporting_documents", []),
            "claim_type": result.claim_type,
            "coverage_assessment": str(result.coverage_assessment),
            "claim_status": str(result.claim_status),
            "potential_exclusions": [item.get("concept", "unknown") for item in result.potential_exclusions],
            "missing_documents": result.missing_documents,
            "evidence": [item.model_dump(mode="json") for item in result.evidence],
            "reasoning_summary": result.reasoning_summary,
        }
        results.append(record)
        print(
            f"[{index:02}/{len(cases)}] {case['id']}: "
            f"{record['coverage_assessment']} / {record['claim_status']}"
        )

    (DEMO_DIR / "results.json").write_text(
        json.dumps(results, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    (DEMO_DIR / "results.md").write_text(render_markdown(results), encoding="utf-8")
    print(f"\nSaved {len(results)} processed cases to {DEMO_DIR / 'results.md'}")


def render_markdown(results: list[dict]) -> str:
    lines = [
        "# Processed demo claims",
        "",
        "Generated by `run_demo_cases.py`. These are preliminary test outcomes, not real insurance decisions.",
        "",
        "| Case | Policy | Claim type | Coverage | Status |",
        "|---|---|---|---|---|",
    ]
    for result in results:
        lines.append(
            f"| {result['id']} | {result['policy']} | {result['claim_type']} | "
            f"{result['coverage_assessment']} | {result['claim_status']} |"
        )
    for result in results:
        lines.extend(
            [
                "",
                f"## {result['title']} (`{result['id']}`)",
                "",
                f"- Description: {result['description']}",
                f"- Expected safety behavior: {result['expected_behavior']}",
                f"- Processed result: `{result['coverage_assessment']}` / `{result['claim_status']}`",
                f"- Detected exclusions: {', '.join(result['potential_exclusions']) or 'none'}",
                f"- Missing documents: {', '.join(result['missing_documents']) or 'none'}",
                f"- Image: `{result['image']}`" if result.get("image") else "- Image: none",
                f"- Supporting documents: {', '.join(result['supporting_documents']) or 'none'}",
                f"- Reasoning: {result['reasoning_summary']}",
            ]
        )
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    main()
